"""empty message

Revision ID: 347075fabbeb
Revises: c23089d3cd15
Create Date: 2021-06-11 23:16:55.876902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347075fabbeb'
down_revision = 'c23089d3cd15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('video_link', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'video_link')
    # ### end Alembic commands ###
